{{- if eq .Values.persistence.claimName "" }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "spaceengineers.fullname" . }}-config
  labels:
    app: {{ template "spaceengineers.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.config.size | quote }}

{{- if .Values.persistence.config.storageClassName }}
  storageClassName: {{ .Values.persistence.config.storageClassName }}
{{- end }}
{{- end }}
