apiVersion: v1
kind: Service
metadata:
  name: {{ template "spaceengineers.fullname" . }}-udp
  labels:
    app: {{ template "spaceengineers.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
  annotations:
    metallb.universe.tf/allow-shared-ip: {{ template "spaceengineers.fullname" . }}
spec:
  type: {{ .Values.spaceengineersServer.serviceType }}
  ports:
  {{- if eq "LoadBalancer" .Values.spaceengineersServer.serviceType }}
  - name: se-udp-1
    port: 27016
    targetPort: se-udp-1
    protocol: UDP
  {{- else }}
  - name: se-1
    port: {{ .Values.spaceengineersServer.serverPort | int }}
    targetPort: se-1
    nodePort: {{ .Values.spaceengineersServer.serverPort | int }}
    protocol: UDP
  {{- end }}
  selector:
    app: {{ template "spaceengineers.fullname" . }}
