# Valheim image version
# ref: https://github.com/rfvgyhn/docker-avorion
image: mmmaxwwwell/space-engineers-dedicated-docker-linux
imageTag: latest

replicaCount: 1

# Configure resource requests and limits
# ref: http://kubernetes.io/docs/user-guide/compute-resources/
resources:
  requests:
    memory: 1024Mi
    cpu: 1000m

persistence:
  config:
    enabled: true
    size: 1Gi
    # storageClassName: -
  claimName: "" # provide a value to prevent PVC creation
